import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Eye, Loader2, ReceiptText, Search } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { listServiceTabs, type ServiceTab } from "@/service/serviceTabService";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dateTime = (value?: string | null) => value ? new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "Não informado";
const dateKey = (value?: string | null) => value ? new Date(value).toLocaleDateString("en-CA") : "";

export function ServiceTabHistoryPage() {
  const [tabs, setTabs] = useState<ServiceTab[]>([]); const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState("");
  const [selected, setSelected] = useState<ServiceTab | null>(null);
  useEffect(() => { listServiceTabs("paid").then(setTabs).catch((error) => toast.error((error as { response?: { data?: { message?: string } } })?.response?.data?.message || "Não foi possível carregar o histórico." )).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase("pt-BR"); return tabs.filter((tab) => { const date = dateKey(tab.closedAt); return (!q || tab.appointment.client.name.toLocaleLowerCase("pt-BR").includes(q) || tab.appointment.barber.displayName.toLocaleLowerCase("pt-BR").includes(q) || tab.id.toLowerCase().includes(q)) && (!startDate || date >= startDate) && (!endDate || date <= endDate); }); }, [tabs, search, startDate, endDate]);
  const total = filtered.reduce((sum, tab) => sum + tab.total, 0);
  return <div className="space-y-6 pb-8"><div><h1 className="text-2xl font-semibold">Histórico de comandas</h1><p className="text-sm text-muted-foreground">Consulte todas as comandas pagas e fechadas da barbearia.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Comandas encontradas</p><strong className="text-2xl">{filtered.length}</strong></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Total recebido</p><strong className="text-2xl">{money(total)}</strong></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Valor médio</p><strong className="text-2xl">{money(filtered.length ? total / filtered.length : 0)}</strong></div></div>
    <div className="space-y-4 rounded-xl border bg-card p-4"><div className="grid gap-3 lg:grid-cols-[1fr_190px_190px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por cliente, barbeiro ou código" className="pl-9" /></div>{[[startDate, setStartDate, "Data inicial"], [endDate, setEndDate, "Data final"]].map(([value, setter, label]) => <div className="relative" key={String(label)}><CalendarDays className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input type="date" aria-label={String(label)} value={String(value)} onChange={(e) => (setter as (v: string) => void)(e.target.value)} className="pl-9" /></div>)}<Button variant="outline" disabled={!search && !startDate && !endDate} onClick={() => { setSearch(""); setStartDate(""); setEndDate(""); }}>Limpar</Button></div>
      {loading ? <div className="grid place-items-center py-16"><Loader2 className="animate-spin" /></div> : !filtered.length ? <div className="py-16 text-center"><ReceiptText className="mx-auto mb-3 text-muted-foreground" /><p>Nenhuma comanda fechada encontrada.</p></div> : <div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Fechamento</TableHead><TableHead>Cliente</TableHead><TableHead>Barbeiro</TableHead><TableHead>Itens</TableHead><TableHead className="text-right">Total</TableHead><TableHead /></TableRow></TableHeader><TableBody>{filtered.map((tab) => <TableRow key={tab.id}><TableCell>{dateTime(tab.closedAt)}</TableCell><TableCell className="font-medium">{tab.appointment.client.name}</TableCell><TableCell>{tab.appointment.barber.displayName}</TableCell><TableCell>{tab.items.reduce((sum, item) => sum + item.quantity, 0)}</TableCell><TableCell className="text-right font-semibold">{money(tab.total)}</TableCell><TableCell><Button size="icon" variant="ghost" onClick={() => setSelected(tab)}><Eye className="h-4 w-4" /></Button></TableCell></TableRow>)}</TableBody></Table></div>}
    </div><Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Detalhes da comanda</DialogTitle></DialogHeader>{selected && <div className="space-y-4"><div className="grid grid-cols-2 gap-3 rounded-lg border p-4"><div><p className="text-xs text-muted-foreground">Cliente</p><strong>{selected.appointment.client.name}</strong></div><div><p className="text-xs text-muted-foreground">Barbeiro</p><strong>{selected.appointment.barber.displayName}</strong></div><div><p className="text-xs text-muted-foreground">Fechada em</p>{dateTime(selected.closedAt)}</div><div><p className="text-xs text-muted-foreground">Status</p><Badge variant="outline">Paga e fechada</Badge></div></div><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Qtd.</TableHead><TableHead className="text-right">Unitário</TableHead><TableHead className="text-right">Subtotal</TableHead></TableRow></TableHeader><TableBody>{selected.items.map((item) => <TableRow key={item.id}><TableCell>{item.name}</TableCell><TableCell>{item.quantity}</TableCell><TableCell className="text-right">{money(item.unitPrice)}</TableCell><TableCell className="text-right">{money(item.total)}</TableCell></TableRow>)}</TableBody></Table><div className="flex justify-between rounded-lg bg-primary/5 p-4"><strong>Total</strong><strong className="text-2xl">{money(selected.total)}</strong></div></div>}</DialogContent></Dialog></div>;
}
